[features]
seeds = false
skip-lint = false

[programs.localnet]
solsociety = "Hagbeh44aCHDPxRD7SrVsnPZUCkRApcYUUqjRLATJruX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/solsociety.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
