[features]
seeds = false
skip-lint = false

[programs.localnet]
solciety_program = "5aK8HrYzjgJrut2xo48NQwbm4DcEn6cceiJjyxxhcW5E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/iqbalutomo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
